name: 萌娘百科内容页面

on:
  schedule:
    - cron: '0 16 1,15 * *'
  workflow_dispatch:

jobs:
  titles:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Fetch titles
      env:
        BOT_NAME: ${{ secrets.BOT_NAME }}
        BOT_PASS: ${{ secrets.BOT_PASS }}
        API_ADDRESS: "https://zh.moegirl.org.cn/api.php?format=json"
      run: |
        python titles.py
    - name: Save titles
      run: |
        git add titles.txt
        git -c user.name=GitHub -c user.email=noreply@github.com commit \
          -m "From GitHub Actions build ${GITHUB_RUN_NUMBER}"
        git push